language: node_js
node_js:
- '8'
- '10'
cache: yarn
script: yarn ci
deploy:
  provider: npm
  email: igor@kamyshev.me
  skip_cleanup: true
  api_key:
    secure: wL4iRgdtAqPH73EqKahfwedfuk0Q+um9KK1W0rGy9FmiIJmKUEIzHgvydNBtSLeStUiVMRVdaLHQLGgHBzQtDhnuJaY+7A1pWcGVmiWzzSUlAo7P3/p5MXUdH8A+ywX9B9zUy4y8QJJdup6y6Jxj7l/gXvopQCR6IuRsMnNhwc9BpT/G/CijzyUYS4On1DtQ0Rl7MXGCcemfiGt2/yJpHepYaGb/GC6wNKYPBjfb8aKeuTclYhM9r84R7e8jeLwrbyOHOFfV2qGHA7/NXBvG63cQRPpKRuwaZ8rSoYXP2Q+lnflqtkD0udLEvV6mqxBmWwDBJmpzu0I/uqZzF+Wb7ORr+tbiSu8XNyRGHW/QjfHfweczoMdvbHpsVF9ME3zmSfwwAjANmpEoQyODTK5HRsSEOGeTP2m37QHzm5o4Z2IZx3dEmJdxWac7FgeTTfZ3ANsVG2d3qv4EdOAj+q6rUVVqdT9iEuVXbgDm/P9fCnWdYYBk4j46r2WwtUrSsBPenKu7vJeavdHb6asD0bkMJjudL53mUJl8HrXJOrO3f+ia6ywkFGinS5qMJYzJR/szqvBPhZy5ZPEKjGRw8fa4nGWrwSb0uIXOQLmR408/LUSOCm7aF+BxD8v5qPz8il0OfMiH8NBYUYcOxDVMYFBndcqBLd0t0xqr349M/qtRIJI=
  on:
    tags: true
    repo: igorkamyshev/only-last
